name = "ZipArchives"
uuid = "49080126-0e18-4c2a-b176-c102e4b3760c"
authors = ["nhz2 <nhz2@cornell.edu>"]
version = "2.5.1"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
CodecInflate64 = "6309b1aa-fc58-479c-8956-599a07234577"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
InputBuffers = "0c81fc1b-5583-44fc-8770-48be1e1cca08"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"
Zlib_jll = "83775a58-1f1d-513f-b197-d71354ab007a"

[compat]
ArgCheck = "2"
CodecInflate64 = "0.1"
CodecZlib = "0.7"
InputBuffers = "1.1"
PrecompileTools = "1"
TranscodingStreams = "0.9, 0.10, 0.11"
Zlib_jll = "1"
julia = "1.6.0"
